version: 2
plan:
  project-key: SAM
  key: PLAN
  name: Build the rockets

# List of plan's stages and jobs
stages:
  - Build the rocket stage:
    - Build

#Job definition
Build:
  tasks:
    - script:
        - echo 'Built it'